# Generated by Django 4.0 on 2021-12-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Usermanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=255)),
                ('Lastname', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('DOB', models.CharField(max_length=255)),
                ('Marital_status', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Address', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('Username',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=255)),
                ('Cost_Price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Selling_Price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Suppliers', models.CharField(max_length=300)),
                ('Tax_method', models.CharField(max_length=255)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Quantity_left', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Quantity_sold', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('Product_name',),
            },
        ),
        migrations.CreateModel(
            name='Salesbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Purchase_number', models.CharField(max_length=255)),
                ('Supplier', models.CharField(max_length=255)),
                ('Vat', models.IntegerField()),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Shipping', models.CharField(max_length=255)),
                ('Payment', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Purchase_note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
        migrations.CreateModel(
            name='Sales_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Purchase_number', models.CharField(max_length=255)),
                ('Supplier', models.CharField(max_length=255)),
                ('Product_name', models.CharField(max_length=255)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Product', models.CharField(max_length=255)),
                ('Customer', models.CharField(max_length=255)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Vat', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Paid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Payment_status', models.CharField(max_length=255)),
                ('Sales_note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Product', models.CharField(max_length=255)),
                ('Customer', models.CharField(max_length=255)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Vat', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Paid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Payment_status', models.CharField(max_length=255)),
                ('Return_note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
        migrations.CreateModel(
            name='Purchase_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Purchase_number', models.CharField(max_length=255)),
                ('Supplier', models.CharField(max_length=255)),
                ('Product_name', models.CharField(max_length=255)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Purchase_number', models.CharField(max_length=255)),
                ('Supplier', models.CharField(max_length=255)),
                ('Vat', models.IntegerField()),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Shipping', models.CharField(max_length=255)),
                ('Payment', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Purchase_note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('-Date',),
            },
        ),
        migrations.CreateModel(
            name='Addbusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.CharField(max_length=1000)),
                ('Business_email', models.EmailField(max_length=254)),
                ('Business_Address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ('Business_name',),
            },
        ),
    ]
